
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # env_file:
    #   - ./backend/.env
    environment:
      - NODE_ENV=production
      - JWT_LIFETIME=30d
      - JWT_SECRET=IcGuR0dBKg5PAdfdreaY9Sqz1VlQw6yFjMv
      - MONGO_URL=mongodb://mongo:27017/jahbd
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - app-net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://server:5000
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    networks:
      - app-net
    depends_on:
      - server
    # environment:
      # - VITE_API_URL=http://server:5000

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
