export { default as AdminDashboard } from './admin/Dashboard'
export { default as AddCollage } from './admin/AddCollage'
export { default as AddMajor } from './admin/AddMajor'
export { default as AddSubject } from './admin/AddSubject'
export { default as Collages } from './admin/Collages'
export { default as CollageInfo } from './admin/CollageInfo'
export { default as MajorInfo } from './admin/MajorInfo'
export { default as Semesters } from './admin/Semesters'
export { default as StudentGrades } from './admin/StudentGrades'
export { default as CreateCourse } from './admin/CreateCourse'
export { default as Semester } from './admin/Semester'
export { default as  AboutCollage} from './admin/AboutCollage'
export { default as  AboutMajor} from './admin/AboutMajor'
export { default as  AddCourse} from './admin/AddCourse'
export { default as AboutSemester } from './admin/AboutSemester'
export { default as Majors } from './admin/Majors'
export { default as Subjects } from './admin/Subjects'
export { default as SemestersTemplate } from './admin/SemestersTemplate'
export { default as SemesterTemplateDetails } from './admin/SemesterTemplateDetails'
export { default as Admins } from './admin/Admins'
export { default as Teachers } from './admin/Teachers'
export { default as Students } from './admin/Students'
export { default as Users } from './admin/Users'
export { default as Course } from './admin/Course'
export { default as Lessons } from './admin/Lessons'
export { default as CourseLesson } from './admin/CourseLesson'
