export { default as AdminDashboard } from './Dashboard'
export { default as AddCollage } from './AddCollage'
export { default as AddMajor } from './AddMajor'
export { default as AddSubject } from './AddSubject'
export { default as Collages } from './Collages'
export { default as CollageInfo } from './CollageInfo'
export { default as MajorInfo } from './MajorInfo'
export { default as Semesters } from './Semesters'
export { default as StudentGrades } from './StudentGrades'
export { default as CreateCourse } from './CreateCourse'
export { default as Semester } from './Semester'
export { default as  AboutCollage} from './AboutCollage'
export { default as  AboutMajor} from './AboutMajor'
export { default as Majors } from './Majors'
export { default as Subjects } from './Subjects'
export { default as SemestersTemplate } from './SemestersTemplate'
export { default as SemesterTemplateDetails } from './SemesterTemplateDetails'
export { default as Admins } from './Admins'
export { default as Teachers } from './Teachers'
export { default as Students } from './Students'
export { default as Users } from './Users'
export { default as Course } from './Course'
export { default as Lessons } from './Lessons'
export { default as CourseLesson } from './CourseLesson'
export { default as StudentProfile } from './StudentProfile'
export { default as UserProfile } from './UserProfile'
